### ISSUE TITLE
MQTT discovery automatic configuration

### ISSUE THREAD

**Issue by djfjeff** [TD22057/insteon-mqtt#128]
Home Assistant has the MQTT discovery component that is able to automatically discover devices and correctly configure them in Home Assistant : https://www.home-assistant.io/docs/mqtt/discovery/

Basically, the device itself is responsible to publish it's configuration on a specific topic through MQTT, providing details about it's configuration. Just doing that will auto-configure the device in HA and the device will be ready to use by the time you open the HA interface!

The MQTT discovery is also not completely tied specifically to Home Assistant. It seems other automation software try to use this and some device already support it too.

I think it would be great to add this to insteon-mqtt. I will try to take a look at it but I wanted to throw the idea out in case someone want to also take a look.

**Comment by TD22057** [comment]
Interesting idea.  Seems like there are a few parts to think about:
1) Config input.  User needs some way to enter the config topic (is it just 1 input?).  Might also need some way to control when this happens.
2) Device supports.  Add a method to each MQTT device to send the config topic.  Questions here would be when should this occur?  Once at each start up?  Any other way seems complicated in that we'd have to keep track of all the settings for a device type and resend the config when any item in that set changes.
3) Command line support.  Probably be useful to have a command line function to trigger sending the config for all devices, all devices of a certain type, or one device.
4) Docs.  Will need to update the config.yaml file w/ examples as well as the device doc page with some explanation for how this works and when someone might want to use it.

**Comment by billchurch** [comment]
I'm very interested in this as well, and would be happy to help with building this out. Is there a roadmap or anything published for this project? Would love to start contributing.

**Comment by TD22057** [comment]
@billchurch You can contribute whenever you like.  We can talk design ideas here.  Start w/ a prototype.  For each device type, send an MQTT message by hand to HA until you can get it to configure the device to work properly using the entries in the IM config file.  Once we know the "right" messages to send, we can work on how and when to send them.  We can store a flag in the device DB meta data file that tells IM if HA needs to be told about the device.  Then we can add a method to each device in mqtt/*.py to send that message if needed.  When that's done, we can create something to check those flags on start up and send the messages automatically.

**Comment by GreatWhiteDan** [comment]
@TD22057 @billchurch 
It is interesting that you just posted that.   I was going to start playing with your code on my own, but I am just an intermediate coder.   I at least understand the code you built, but modifying it might be difficult.    As far as this MQTT components, I do understand that.   And here is what I did last night.

The biggest issue I had with MQTT in the yml, is that at least for me, it does not actually create a device.  Therefore, I can see the insteon item in lovelace for the dashboard, but it does not exist under devices, so it can not be used in automation or other components of HASS.

Using MQTT Explorer, I was looking at the way zigbee2mqtt did this.  There is a yml config that sets homeassistant: true and this it post all updates to the zigbee2mqtt subscription, but also, it sends out configuration on an interval.   Not sure what the timer is, but here is an example on insteon that worked perfectly.

published to:
homeassistant/light/32fde4/light/config

json:
{
	"brightness":true,
	"schema":"json",
	"command_topic":"insteon/32.fd.e4/set/1",
	"state_topic":"insteon/32.fd.e4/state/1",
	"json_attributes_topic":"zigbee2mqtt/0xf0d1b800000749fb",
	"name":"32fde4_light",
	"unique_id":"32fde4_light_insteon2mqtt",
	"device":{
		"identifiers":[
			"insteon2mqtt_32fde4"
		],
		"name":"Attic Chandeler",
		"model":"2334-232",
		"manufacturer":"Insteon"
	}
}

Each devices is sent out in the format and it autodiscovers perfectly.   I can try hacking on your code some, but I would be afraid to share it.... ;p

**Comment by jstebbins** [comment]
I just created an HA mqtt gateway for a Vantage inFusion system that uses mqtt discovery.  I'm also interested in discovery for Insteon since I have those as well and would like the whole thing working through MQTT.  

The project is still a work in progress, but it's here for reference https://github.com/jstebbins/hassio-vantage2mqtt. src/hamqtt.py is the main interface for registering devices.

As far as topics for registration go, HA defines device registration topics as `<discovery_prefix>/<component>/[<node_id>/]<object_id>/config` where `discovery_prefix` may be set in mqtt config, but defaults to `homeassistant`. `component` is one of the recognized HA device types. `node_id` is whatever you want, I used it for a "site name", but it's anything to distinguish *your* object ids from someone else.  object_id can be insteon device address.

Each `component` type has a dictionary object (defined by HA) you send during registration to describe that particular components capabilities and what topic it will respond to for commands and what topic it will publish for status.  Complex components generally allow defining a json schema for settings and status.

As for when to register, the HA docs say this:

```
The embedded MQTT broker does not save any messages between restarts. If you use the
embedded MQTT broker you have to send the MQTT discovery messages after every Home
Assistant restart for the devices to show up.
```

So I register every time I reconnect to the MQTT broker.

I haven't started looking at your code yet to see where publishing of discovery config topics would wedge in best.  But since I just installed insteon-mqtt **then** realized it didn't do discovery, I guess I'm committed :wink: I've still got work to do on my Vantage gateway, so I may not dig into this immediately.  But soonish I may start working on a PR.

**Comment by jstebbins** [comment]
> Command line support. Probably be useful to have a command line function to trigger sending the config for all devices, all devices of a certain type, or one device.

Regarding this, I created some special topics my gateway responds to for flush (unregister devices), register (re-register devices), and reload all (flush, re-read configuration from vantage, re-register).  I didn't make them device type specific (it just does all devices), but the topic structure would certainly allow for that extension.  Like I said, it's a work in progress and I'll probably add more specificity to these commands at some point.

**Comment by jstebbins** [comment]
Another thought occurs to me.  Insteon devices like the KeypadLink are really composite devices that contain multiple buttons, and directly control a single load. These should be split into multiple HA devices.  I.e. each button is it's own HA `switch` and the load an HA `light`.  So your object ids should probably be a composite of the insteon address and something to designate which "button" or "load" is being controlled.  You *could* do this splitting via the `node_id` but then you increase the odds of namespace collision with some other mqtt discovery addon. e.g. I can guarantee no namespace collision because my "site name" can be set to something unique in the addon's config.

**Comment by jstebbins** [comment]
Been reading the code a bit. I've got a question.  

It looks like insteon-mqtt has the ability to build a list of devices from the all-link database (refresh and refresh_all), but it currently only uses devices that are configured in config.yaml (i.e. only calls signal_new_device for devices listed in config.yaml).  

Is there a reason for this?  For my application, it would ideally construct the list of devices by reading the all-link database and then register those with HA through mqtt discovery.

**Comment by schirner** [comment]
First of all, great work with this project. Well done. 

I am also very interested in the auto discovery feature. I have too many devices and don't like repetitive work. Hence, I played a bit and took a stab at the discovery feature. Thanks for the detailed discussions here, it allowed me to get an idea how to approach it.

Please see my [discovery branch](https://github.com/schirner/insteon-mqtt/tree/discovery). So far, I have implemented it for Dimmer, Switch, KeypadLinc and Motion detector. Devices and entities show up in HA and things seem generally to work. I am happy so far.

My implementation hooks into the Mqtt object in insteon-mqtt that has a list of all devices ```self.devices```. Each device type implements its own announce, and common functionality (getting device info) is captured in util.py. I managed to get the entities grouped into devices. 

To get started, please see point 9 in [hassio_quick_start](https://github.com/schirner/insteon-mqtt/blob/discovery/docs/hassio_quick_start.md)

While this is not yet complete, I think it is good to share and get feedback.

**Comment by philletourneau** [comment]
This would be a great addition, I'd like to regain some of the frontend configuration you get in Home Assistant when `unique_id` is set.

**Comment by krkeegan** [comment]
I am interested in this, but have a few design questions:

1. The announce register.

Can the discovery messages be set to retain=true?  Does that solve the need to do a announce register?  I imagine this could create an issue with deleted devices?  Maybe, insteon-mqtt deletes everything in the topic on load and then publishes with retain?

2. Templating

This seems maybe a bit to hard coded.  I think it might be better if the payloads were in templates.  

A simple implementation would be to add to the mqtt definition, where we already define what the payloads of the various topics look like.

It would also be nice if we could override definitions for specific devices.  For example, for a number of my switches, I would prefer that they be setup as lights without dimming capability.  This might be a harder thing to do.

**Comment by MrGibbage** [comment]
Newbie here to Home Assistant. Today it occurred to me that I really needed to make the devices in my insteon-mqtt installation visible as entities within HASS. So I did some googling and I found out this really cool thing called "MQTT Discovery". Did some more googling and found out HASS supports it. I watched a few videos and saw people automagically adding their MQTT devices into HASS. And then I ended up here. So you guys are actually working on this?? Nice!

I installed HASS as an image, and insteon-mqtt through the add-on store. Is there a way I can start using the discovery branch? All I need is switches and dimmers (and PLM of course). Do we expect discovery to be a part of a release soon?

In case I decide to not wait for your wonderful work to be done, can someone please post some configuration examples for folks that want to try manually adding their insteon devices?

**Comment by schirner** [comment]
@krkeegan Thanks for your reply and interest. 

**Announce register**. 

Initially, I had the same thought as you. Making the message persistent (retain=true) should work as well for the use case that HA restarts while MQTT broker stays up. However then I realized, it does not cover the case that first MQTT broker restarts, and later (after arbitrary time) HA restarts. In this case HA cannot know about the devices. It will be very difficult for the user to guess the reason as broker restart may have been much earlier. I also liked it the ability to control announce/unannounced in the development phase as this can remove the devices from HA and re-add them slightly differently. This system works well since June through multiple updates (HA and insteon-mqtt config) and power outages.

**Templating**. 

Yes, there is a difference to the current code base which extensively uses templates. My design decision was initially based on development effort. I just did not want to have the extra layer of complexity when developing. However, since HA requires a certain format and offers GUI configuration (each entity as a unique ID so it can be configured in HA), I do see less of a need to template. My Insteon network has grown since June and I have not changed the code for it. 

I see your use case of wanting to use some dimmers as switches. I have the same, I plugged in non-dimmable loads to a dimmer. Unfortunately, templates would not help. Templates are the same for all instances of the same type. Hence, you could only make all dimmers appear as switches but not some. Unfortunately, I don't see the configuration capability in HA Lovelace GUI. So this would require modifying HA’s configure.yaml. If we want to automate your use case, we would need to add an attribute to the confg.yaml devices->dimmer. 

Nonetheless, there are some more complex scenarios (way beyond templates). This has generally to do with Insteon scenes (e.g. 3-way, or keypad button controlled loads) as they are multiple entities, but just one load. Instead of having each controlling switch/dimmer show up in HA, it makes more sense to have only the actual load appear in HA. For those, I manually added a new entity to HA’s configure.yaml, using the modem scene to trigger on/off  and the load to get the state (and disabled the discovered switches / dimmers through Lovelace). 
So overall, discovery in insteon-mqtt very useful for the bulk. Since the format required by HA is more or less fixed, there is diminishing value of templating discovery from insteon-mqtt. Making discovery using templates is not straight forward. It already utilizes existing templates (mqtt topics). To give real templating power we would need to implement and document nested templating. Then, the question becomes how many users will use this – I think it is easier to enter the special cases manually to HA’s configure.yaml.

**Comment by schirner** [comment]
@krkeegan thanks for the hint about retain=true! Writing my reply and then updating my discovery branch made me think again. Happy to be wrong. 

Device presence is announced when insteon-mqtt registers to the MQTT broker. Hence, if the broker restarts while insteon-mqtt stays up, insteon-mqtt re-sends the announcements after registering to the broker again. I changed the code to retain=True, and tested both use cases: 

 1. Home Assistant restart while Mosquitto stays up
 2. Mosquitto restart, followed by HA restart.

Both work! In result, I could simplify the instructions. Now, the user no longer has to add the automation. It just works. Thanks for your suggestion.

**Comment by krkeegan** [comment]
Awesome, that sounds like a much simpler solution.

As to templating this is my thought.  
1. Define a new top level key in the Insteon-MQTT config file say `discovery`
2. Have keys for each device type in here so `Dimmer` `Switch` `KeypadLinc` we can use references if some of these are identical.
3. The devices keys would then define a template for the discovery payload that is sent to HA.  For example a `dimmer` template would then look like:
```
{
  "name": "{{name}}",
  "unique_id": "{{address}}",
  "cmd_t": "{{set_topic}}",
  "stat_t": "{{state_topic}}",
  "schema": "json",
  "brightness": true
}
```
4. The templates would be passed a defined series of values `name` `address` `set_topic` `state_topic` and whatever else is needed.
5. Each Insteon device type will have a default discovery template.  Users can alter the global template for example if they don't want to support dimming.  Or if some other attributes are accepted by HA that a user wants to set.  For example, I think I want all of my Switches to appear as `lights` in HA with the `brightness: false` set.  Most of my switches are CFL lights.  I would like to get the light icon in HA, and when I integrate those objects into Google Home they won't appear as lights unless they are in the light domain.
6. __This is the novelty part__ Users can also alter which template is used on a per-device basis under the `devices` key.  Right now the device looks like `- 0D.74.F1: "my_switch"` But if a user wanted this device to appear in HA as a `light` they could make the config.yaml entry 
```yaml
  - 0D.74.F1:
    name: "my_switch"
    discovery: "special_template
```
7. A user could then add a template to the discovery section called `special_template` and define what they want to appear in the discovery payload for HA.

That is my broad thoughts.  I realize it gets more complicated that this
- We also have to define a component type for each template outside the payload template
- I am not sure how to handle complex devices like IOLincs or even KeypadLincs that may generate multiple HA objects for each Insteon device.

**Comment by krkeegan** [comment]
I forgot to add this would also enable if some other platform openHAB ever supports a similar type of MQTT discovery a user to be able to alter the template to make it compatible.

**Comment by MrGibbage** [comment]
I'm understanding about 5% of what you have written in these last few posts. If they say what I HOPE they say, we (you?) are getting close to being able to turn insteon-mqtt devices and scenes into real HASS entities? Because I think that in order for the nabucasa cloud to be able to control my devices and scenes through insteon-mqtt, I will need to have the devices and scenes appear as entities in HASS, correct?

**Comment by krkeegan** [comment]
I am not sure what you mean by "real HASS entities."  HA allows you to define entities from MQTT topics.

Let's keep this issue focused on discovery.  If you have questions re Insteon-MQTT please use the [discussions](https://github.com/TD22057/insteon-mqtt/discussions) if they are for Home Assistant try their [forums](https://community.home-assistant.io/)

**Comment by schirner** [comment]
I think I am with  you on 1 ... 5. 

How to capture the **component type** (HASS): I would also encode the discovery topic as a template (which contains the component type). Each insteon device type in config.yaml would get a ```discovery_topic``` and ```discovery_payload```.  This is nicely symmetric to all other *_topic, *_payload definitions. 

For complex devices that generate multiple HA entities, I would add additional qualifiers, e.g. keypads would in addition get a ```discovery_btn_topic``` and a ```discovery_btn_payload```.

To get a feel for how it could look, please see [config.yaml](https://github.com/schirner/insteon-mqtt/commit/0124fe942ce89031d6233cd490caf9e3f767bc40#diff-d8d0422389f03d783e32e627250fe29834bd09c6361640d1ff00661dd6820034) on my branch. 

Note that HASS has the device concept. Each device can have multiple entities. For this I added the ```discovery_device_info``` in the common section and reference it in the device type specific templates.

Getting this to run is quiet a bit of work. 

Points 6,7  (the novelty): I would not attempt the device instance specific stuff. This can be a future version. I think it is good to deliver early and often rather than in one big chunk and late.

Philosophically, I am also not in favor of having a template per special instance. Having templates with conditionals would make more sense (e.g. ```{% if dimmable is "true" %} ... ```). This way, the user needs only to maintain one (more complex) template per type, rather than dealing with a copy of the template for any special case instance. But regardless, this is much further down the road.

**Comment by krkeegan** [comment]
I am working on this.  In the process, I discovered (pun intended) a small wrinkle.

The design publishes the discovery messages with `retain = True`. This ensures, that if HA is restarted or InsteonMQTT boots first, that when HA comes online it will see the discovery messages and configure the devices.  I looked at other platforms (about 3 of them) that also use discovery and they also set `retain = True` so we are in decent company.

__The problem__ is that retained messages have an infinite life.  So, if a user has a device `aa.bb.cc` that they use for a while, but at some point replace it the discovery message for `aa.bb.cc` is going to still be there unless we affirmatively delete it.  Solutions include:
1. Delete all discovery topics on shutdown of InsteonMQTT.  I plan on trying this, but I don't know how orderly the shutdown is within HA.
2. Delete all prior topics on startup of InsteonMQTT.  This can only be done if we adopt some sort of prefix for the unique_ids, otherwise we can't distinguish devices added by InsteonMQTT or via some other Integration.  This probably works, but it seems inelegant to me.

Those are the only two ideas I can think of.  Speak up if you have an idea.  If we don't do option 2, I suspect there will at least be some cases where a user will have to manually delete the topic perhaps by using `mosquitto_pub` or maybe by adding a command into InsteonMQTT if it turns out to be a common issue.

**Comment by krkeegan** [comment]
Hmm, more issues.  So to delete a retained message on the broker, you have to publish a message with 0-length payload and the retained flag set.

But it seems HA upon receiving deletes the entity from the HA registry.  This means all associated data icon, area, friendly name, is discarded.  It doesn't matter that a device with the same unique_id is added shortly thereafter.

I have also noticed that you can cause funny things to happen in HA if you change the `unique_id` published under a config topic

**Comment by TD22057** [comment]
What about having a command line option to clear all IM created discovery items with an optional ID input to clear one item.  That would make it more clear that you're going to lose all history and not be automatic on startup/shutdown.

**Comment by krkeegan** [comment]
Alright some good news.  HomeAssistant publishes it's status to the topic `homeassistant/status` with values `offline` or `online`. I think that means we can publish with `retain=False` and monitor the status topic for the payload `online`. When that arrives we can re-push our discovery topics.  It looks like `online` isn't published until __everything__ is loaded in HA, so there shouldn't be any error relying on this.

This seems like a better outcome.  Any discovery issues would be solvable by in the worst case restarting both HA and IM.

**Comment by schirner** [comment]
Awesome! Great to hear that you are working on this. Sorry, I did not manage to keep up with your development and my discovery branch is still on 0.7.5. Hopefully, it still helps to lift some code snippets / ideas from. Thanks in advance for all your work!

I have been running my non-templated version of discovery a while now. Trouble did arise, as  you describe, due to: device rename, device deletion (e.g. device dies). Issue is that HA then still has the lingering old devices and entities. As a work around I manually rename or delete (ignore) in HA. 

Reading your earlier posts, completely deleting the discovery topics seems to have unwanted side effects. Your approach to send discovery after HA comes up implies that removed devices will simply not be announced again. In this case HA cannot know if the device was deleted or the discovery message was just not yet received. In result, I believe those devices remain in HA as unavailable and greyed out (but not deleted). This is very similar to what I tried earlier (before you recommended retain = true).

Since you say that HA actually deletes a device when deleting the discovery message, this (i.e. retain=True + eventual delete) seems the more suitable approach if one wants to explicitly delete a device.  One could think of a more granular approach considering device rename and delete as use cases (any others?).

Device rename happened a few times as I move plugin dimmers around for different purposes (xmas tree).   A simple improvement over my attempts might already be sufficient. Instead of posting to a topic that contains the name, just include the address. So instead of 

```discovery_topic: '{{discovery_topic_base}}/switch/{{name}}/config'```

which I did and I think leads to the renaming problems (and most likely the `unique_id` side effects), one could post to: 

```discovery_topic: '{{discovery_topic_base}}/switch/{{address}}/config'```

This way the topic itself stays the same (so does the Unique ID), only the name changes in the payload. This probably triggers HA to change the name. I have not tried yet, but it would be very logical. I found a similar topic naming in [wyzesense2mqtt](https://github.com/raetha/wyzesense2mqtt) which I randomly checked.

Device deletion: A very elegant version would be if insteon-mqtt could check on startup the difference between the device database (storage) and config.yaml file. If the DB still has device that is no longer in the config.yaml, it must have been deleted. Then, the discovery topics could be deleted, and the DB entry removed. I think [wyzesense2mqtt](https://github.com/raetha/wyzesense2mqtt), might use a similar principle on sensor delete, but triggered by an explicit request.

**Comment by krkeegan** [comment]
> Your approach to send discovery after HA comes up implies that removed devices will simply not be announced again. In this case HA cannot know if the device was deleted or the discovery message was just not yet received. In result, I believe those devices remain in HA as unavailable and greyed out (but not deleted).

This is true.  When HA reboots if it does not see the expected `unique_id` in the discovery topics the entity is displayed in the front end but is grey out.  Inside Config->Integration->Mqtt the entity is displayed with a red circle, with a notation that the device has not been seen.  You are then able to delete this device completely from HA.  This seems like a reasonably user friendly approach:

1. IM is never actively deleting data from HA (so we don't have responsibility for data integrity); and
2. The user has a nice GUI to control deleting an old device.

Things still to check:
1. what happens if a `unique_id` moves from one component (switch, light, fan,...) to another. 

Things I have tested:
1. Moving a `unique_id` from one discovery topic to another works, but it requires a reboot of HA.  Without rebooting HA complains that the `unique_id` is used twice.
2. Renaming a device or changing any of the other settings (model, firmware, topics, areas, templates) can all be done without rebooting HA.  The only critical thing, is that the `unique_id` cannot change.  So I think the best thing is to create the `unique_id` from the device address as the base.  This way, even if you move a device around it shouldn't need to be deleted and recreated.

> A simple improvement over my attempts might already be sufficient. Instead of posting to a topic that contains the name, just include the address.

Agree.  Although it turns out the topic can change as long as HA is rebooted.  But the `unique_id` has to remain the same.  I think we are both on to the same idea here.

> Device deletion: A very elegant version would be if insteon-mqtt could check on startup the difference between the device database (storage) and config.yaml file. If the DB still has device that is no longer in the config.yaml, it must have been deleted.

That is an interesting idea.  But this would only be necessary if we used `retain=True` and I think my preference is to leave it up to the user to delete an abandoned entity within HA.

However, if my plan doesn't work, we may come back to this idea.

**Comment by schirner** [comment]
Sounds great. Thanks for sharing all your findings! 

Yes, my suggestion about device delete triggered from diff between config.yaml and DB only applies to 'retain=True'. But I like your approach ('retain=False') too since the HA user sees the device greyed out and can act on it. There is another argument for 'retain=False': assume insteon-mqtt is down (e.g. due to failure or configuration) when HA comes up. Then all insteon devices will be greyed out. A very clear signal to the HA user, very explicit. 

Thanks for all your hard work! #381 Yay!!!

**Comment by schirner** [comment]
Awesome! Thanks a lot for all your work. Can't wait to try it out and switch to the official release. Now that my semester is done I hopefully find time to play a bit more.
