### ISSUE TITLE
hassio addon 0.6.7 install

### ISSUE THREAD

**Issue by jbarneson** [TD22057/insteon-mqtt#131]
looks like the hassio addon instructions fail to pull from @lnr0626's repository. Is it just me? or can we get an updated build?

**Comment by lnr0626** [comment]
see #122 

the [tags for 0.6.7](https://hub.docker.com/r/lnr0626/armhf-insteon-mqtt/tags) are on dockerhub

**Comment by jbarneson** [comment]
Thanks for responding! I'm still having trouble for some reason, here's my log.. any suggestions?

`19-03-13 22:30:53 ERROR (SyncWorker_18) [hassio.docker.interface] Can't install lnr0626/armv7-insteon-mqtt:0.6.7 -> 404 Client Error: Not Found ("pull access denied for lnr0626/armv7-insteon-mqtt, repository does not exist or may require 'docker login'").`

**Comment by jbarneson** [comment]
i changed my architecture from 
    "image": "lnr0626/{arch}-insteon-mqtt"
to:
    "image": "lnr0626/armhf-insteon-mqtt"

and nothing seems to be wrong. Not sure what the build difference might be from armv7 and armhf though..

**Comment by lnr0626** [comment]
What platform are you running hassio on?

**Comment by lnr0626** [comment]
Which model of rpi? There's a few.

Hassio's add-on image builder doesn't create images for armv7 (which implies to me it's not really supported), and so it's possible that the issues stem from the same thing that's causing your system to report it's architecture as armv7. The rpi 3 b+ should be armhf, but I'm not sure about the other ones

**Comment by djryan012** [comment]
Also having issues with leaving {arch} as default. Running on Pi 3 model B. My error logs show as follows and notice that its now pulling armv7 instead of armhf which was addon v0.6.4 When I changed arch back to armhf 0.6.7 installed just fine.

19-03-16 05:42:01 INFO (SyncWorker_5) [hassio.docker.interface] Update Docker lnr0626/armhf-insteon-mqtt:0.6.4 to lnr0626/armv7-insteon-mqtt:0.6.6
19-03-16 05:42:01 INFO (SyncWorker_5) [hassio.docker.interface] Pull image lnr0626/armv7-insteon-mqtt tag 0.6.6.
19-03-16 05:42:02 ERROR (SyncWorker_5) [hassio.docker.interface] Can't install lnr0626/armv7-insteon-mqtt:0.6.6 -> 404 Client Error: Not Found ("pull access denied for lnr0626/armv7-insteon-mqtt, repository does not exist or may require 'docker login'").

**Comment by lnr0626** [comment]
tags for 0.6.6 don't exist - the releases aren't tagged, and so when I miss a release it's non trivial to go back and build images for that release

**Comment by TD22057** [comment]
@lnr0626 FYI - I didn't realize that tags weren't getting pushed (I was creating them locally).  I pushed tags for 0.6.6, 0.6.7, and 0.6.8 just now.
