### ISSUE TITLE
Does this allow local device changes to sync back to Home Assistant?

### ISSUE THREAD

**Issue by blysik** [TD22057/insteon-mqtt#133]
Hi,

I'm a user of Indigo and Insteon (via a 2413U), but I'm considering switching to Home Assistant.  The HomeKit component, vending out Insteon devices is important to me.  However, I've heard that the built in component insteonplm for HA wouldn't sync back local device changes (like if I manually flipped a light switch) back to HA.

Because I need HomeKit to reflect the current state as best I can, this is important to me. 

However, I found this project, and wonder if this is a better solution.  Does it listen and reflect in mqtt the changes that are made at a device?

Thanks!

**Comment by TD22057** [comment]
Yes it does.  As far as I know, the built in HA component does that as well.  I wrote this to give a platform independent way to use Insteon, give access to lower level commands for configuring the devices, and to instantly update connected scenes (it updates all connected devices in the scene automatically rather than polling devices to see their states).
