### ISSUE TITLE
Consuming 100% CPU

### ISSUE THREAD

**Issue by dlarrick** [TD22057/insteon-mqtt#195]
Greetings,

Since 0.70 upgrade, insteon-mqtt is working fine for me but consuming 100% of one core on my system.

It's looping continuously in the main network event loop. If I add a time.sleep(0.05) at the end of the loop at the bottom of start.py the problem goes away, but I am not at all clear that this is a correct fix or just a bandaid hiding the real problem.

**Comment by TD22057** [comment]
@krkeegan 

There was a new construct introduced to help w/ scene syncing that interfaces with the network event loop.  I'm guessing it's something to do with that.  I'll take a look later today and get it fixed ASAP.

**Comment by TD22057** [comment]
Diagnosis: the new stack class uses a temporary file to get a fileno because that's what the network select code requires.  But that means the file is always available to read from so the event loop keeps trying to read.  I think the fix is to change the network event loop to allow a None fileno and only poll the stack instead of triggering on read/write like a socket.

**Comment by dlarrick** [comment]
Awesome, thanks for the quick turnaround!

**Comment by krkeegan** [comment]
Wow, nice fix.  Sorry to have created such a bug. Somehow that didn't happen to me.
