### ISSUE TITLE
Readme has outdated MQTT topic information?

### ISSUE THREAD

**Issue by bfranske** [TD22057/insteon-mqtt#2]
I was not able to use the insteon/state/AA.BB.CC and insteon/set/AA.BB.CC topics to control a device with the payload "cmd..." as described in the Readme. Instead I needed to use as something like insteon/AA.BB.CC/set" -m '{ "state" : "on" } Since this looks like it is under pretty active development I'm guessing that the documentation just hasn't caught up yet. If things are starting to stabilize I'm willing to try and work on some more documentation (see my pull request as a start) as time allows and as I implement this myself.

**Comment by TD22057** [comment]
Take a look now - first cut of a doc rewrite is up.

**Comment by bfranske** [comment]
Thanks! I was actually having a read through it already when I saw this. I haven't downloaded the latest files and tried yet but in the documentation I'm already finding a few inconsistencies from one file to another, and a few typos of course. Do you have a preference as to me filing as issues or fixing and then creating a pull request?

**Comment by TD22057** [comment]
Whatever is simplest for you.  Pull request is fine - just be sure to switch to the dev branch.  Since this should be reasonably stable now, I've changed the master to be for the released versions.  Thanks for the help and feel free to let me know if you want any other devices added.  Most should be pretty simple (except the thermostat which looks very complicated).
