### ISSUE TITLE
Will this work with Insteon 2448A7 for the PLM?

### ISSUE THREAD

**Issue by jonsmirl** [TD22057/insteon-mqtt#226]
Will this work with Insteon 2448A7 for the PLM?

**Comment by TD22057** [comment]
Probably provided you meet it's requirements (of having an a dual band device) - but I don't know of anyone who's tested it.  But it does say "Since this is a RF only device, for always on applications, we highly recommend the plug-in dual-band version for superior performance and reliability." so why not just get the USB PLM?
