### ISSUE TITLE
Support for X10 devices

### ISSUE THREAD

**Issue by bfranske** [TD22057/insteon-mqtt#26]
This is a nice to have, I know of a few people (like my parents) still controlling some X10 devices with an Insteon PLM. Obviously this is probably an ever-shrinking group of people but it is an advertised feature of Insteon and is probably not terribly difficult to implement so in the interest of a full Insteon implementation we should probably try to offer some basic X10 device support.

**Comment by TD22057** [comment]
FYI - I don't have any X10 devices and I'm probably not going to buy any just to support them.  So the only way I see this happening is if someone else wants to write some code and submit a pull request.

**Comment by rperciaccante** [comment]
Give me an address and a few days, I can send you one or two to tinker
with.  I may not be able to write code, but I would be happy to help the
cause

Bob

**Comment by TD22057** [comment]
Thanks for the offer - but I want to focus my time on documentation and test cases right now.   The X10 messages look non-trivial to implement (at least at first glance) and since I have no real use for them, I have a hard time thinking I'll ever carve out the time to add them.  I'd be happy to merge in any pull requests or help with any questions for someone who does want to add them.

**Comment by bfranske** [comment]
FYI If someone wants to work on this at some point. openHAB seems to have X10 support in their [InsteonPLM binding](https://github.com/openhab/openhab1-addons/tree/master/bundles/binding/org.openhab.binding.insteonplm) so that may provide some implementation cues.

**Comment by JonS9999** [comment]
FYI, I've been playing around with adding X10 support to this.  I have an Insteon USB "Modem" (2413U) connected to a Raspberry Pi (running OpenHab and Node Red).  I have insteon-mqtt running stand alone on the Pi, and I'm able to watch for and parse X10 messages that arrive via the 2413U. 

Things I have left to do :

   - Now that I can receive and parse the inbound X10 message (as described above), pass the X10 message on to the local MQTT broker.  This will allow Node Red to receive the X10 message (via MQTT) and take whatever action I want.

   - Add support to receive X10 commands from MQTT and send the commands out the 2413U.  This is not a high priority for me, so it falls into the "If I get a chance to do it" bucket...

Would this stuff be of any use/interest to anyone?

Cheers.

-Jon

**Comment by bfranske** [comment]
@JonS9999 Yes, I'm sure it would be. If you have working X10 support please create a pull request for it.

**Comment by glyndon** [comment]
FWIW, the native Insteon PLM integration for HomeAssistant also has X-10 support, thanks to teharris' work on it. I helped test the function of it when responding to old X-10 keypad events, it works well.

**Comment by dcossey014** [comment]
I have X10 devices, and the 2413U PLM.  I would be interested in this work as well as contributing to it.  Let me know how I could help.

**Comment by TD22057** [comment]
@dcossey014 : As I said, I'm happy to provide support but have no devices myself so you'll have to do the coding yourself and then make a pull request.

@JonS9999 : where is the repo with your X10 code in it?  It would be a big help if you could push that to github so everyone can see it.

**Comment by dcossey014** [comment]
@TD22057 :  I'll be more than happy to do the coding for it.  But there's no guarantee I'll get to it any time soon.  Between kids, work, and trying to stand up a new server cluster I do not have much free time.  My current setup is running on macOS and I do not like the fact that I cannot setup service accounts for HASS, mosquito, and insteon-mqtt.  I prefer my services not to be run on accounts that have login privileges.  It's part of the reason I'm building a new Proxmox setup.

**Comment by krkeegan** [comment]
I am marking this as a wontfix.  I am with Ted, I don't have X10 devices, if someone wants to step up and write the support for them that would be great.  It is mildly non-trivial as whatever support would probably also have to alter much of the underlying device support as everything is assumed to be an insteon device currently.

Since this garnered some conversation I will leave this open for a while.

**Comment by dcossey014** [comment]
@krkeegan That's not an issue.  In the last year, I've been slammed with work and setting up a home office for working from home.  As well as duplicating a cluster environment to mimic my work cluster for testing things from my home Office.   Let's just say this past year has been interesting.  I have had little to zero time to put effort into digging into the code and setting up any of my X10 devices.  I think I've replaced most of those devices with Zwave and Insteon devices anyway since X10 is difficult to find.  Do we have an approximate User base that is interested in this?  Or is this a minor fringe that is shrinking daily?

**Comment by krkeegan** [comment]
My impression is that there are very few remaining X10 users, I have not seen any other interest on this project beyond what you see here.

**Comment by dcossey014** [comment]
That is my impression as well.  I say focus should be on moving forward with expanding the Insteon Integration and support.

**Comment by JonS9999** [comment]
I've been a fly-on-the-wall on this conversation for some time.  I had been a long-time X10 user (from since the 70's), but within the last year things the X10 stuff has gotten more and more unreliable.  I have a feeling it's because I've been swapping out incandescent bulbs with LEDs, and (just a guess here) the new bulbs generate a bunch of noise on the lines which kills the X10 signals.

My eventual goal was to do a DIY approach using ESP8266/ESP32 based solutions, but (like others in this thread) I, too, have been slammed with work and such during this past year, so I have near-zero free time to work on things.  I'm having to just suck it up and buy off-the-shelve Alexa aware switches and go that route.  That approach is more reliable, but much less flexible as I don't have an easy way to control or listen to the Alexa stuff from NodeRED.

Thank you, everyone, for your attention to the X10 support on this project, but yeah, feel free to mark it as 'do not fix'.

Take care, stay safe and have a good day.

-Jon
