### ISSUE TITLE
State tracking out of sync when using 3-way switch style links

### ISSUE THREAD

**Issue by bfranske** [TD22057/insteon-mqtt#30]
So I've been spending a fair amount of time playing with this today and have discovered a situation where the state of a device (in this case a dimmer) is not being tracked.

Steps to reproduce:
1. Turn on light from the primary dimmer (the one which is actually controlling the light), notice the MQTT message is sent that the state is on and HASS shows the light as on
1. Turn off light from another switch (controller) which sends an insteon message to the primary dimmer (responder), notice there is no MQTT message sent and so HASS, etc. assumes the light is still on even though it is not
1. Press the off button from the primary dimmer (the one which is actually controlling the light), notice the MQTT message is sent that the state is off and HASS shows the light as off
1. Turn on light from another switch (controller) which sends an insteon message to the primary dimmer (responder), notice there is no MQTT message sent and so HASS, etc. assumes the light is still off even though it is on

So, how to fix? It seems like the PLM should be able to see messages on the Insteon network going from a controller to a responder so if it sees an off message going to the responder it should send an MQTT message noting the light is now off.

Note, this may be being further confused by Insteon scenes. All of my links between controllers and responders were originally created by Mr House (see #25) so the controllers may actually be sending a scene control message. In that case I would think the PLM should be listening for the scene change message and ideally updating the status of each scene responder device. Note too that this probably requires implementing #25 so that the configuration file contains a list of all responders to each scene, though you might be able to pull this from the link databases on the devices I suppose.

Of course I may be way off base and missing something simpler here too.

**Comment by TD22057** [comment]
FYI - that's not how it works.  The modem only sees messages that are sent to the modem.  So you have to call pair() for every device or have created those links yourself.  The modem must be the group 1 controller and group 1-n responder for every device on the network.  And the insteon-mqtt system needs to have called refresh() for each device so that it has a copy of the all link database so it knows about the 3-way relationships.  Try running `insteon-mqtt config.yaml print-db aa.bb.cc` on each device and make sure they are sending messages to the modem.  You can also watch the logs as you click the buttons to see if a broadcast messages arrives for each click.

**Comment by bfranske** [comment]
Thanks for the additional details, I'll check it out. It seems like the status was reporting correctly when I was using Mr House so I think the modem is receiving the messages but I'll double check.

**Comment by TD22057** [comment]
OK - glad that's all it was.
