### ISSUE TITLE
Add Auto Adjusting Max Hops

### ISSUE THREAD

**Issue by krkeegan** [TD22057/insteon-mqtt#43]
It looks like most if not all of the messages sent out by the code have the max_hops field set to 3.  This isn't really a good idea for real world use for a couple reasons:

- It adds an extra delay before the device will respond, the device will wait until the amount of time for all hops to have taken place before responding.
- It creates the potential for lost messages because of all of the yelling on the network.
- But most importantly, it creates the possibility of confusion because of duplicate messages.

A solution that has worked for this before is to calculate hops using a rolling average (10 messages seems to work well, without being to slow to respond to changes).  It works like this:

- On each incoming message use the max_hops and hops_left flags to calculate the total number of hops that was necessary for that message to reach us.
  - Only keep the 10 most recent values, dropping the oldest value off the end of the list
- When sending a message, calculate the average hops from the above list, and round up.
  - Use this value as the max hops when sending the message
  - If any retries are necessary, increment the max_hops by 1 if permitted.

**Comment by krkeegan** [comment]
Hmm, this one has also stumped me.

I tried placing the logic for parsing the hops tracking at the protocol level.  But nothing at that level has any access to the modem object and so we can't call find() to access the device object for storing the hops_left counts.

My next thought is to insert a subclass in the handlers.  It would be Base->DirectMsg->(DeviceDB*, DeviceRefresh, StandardCmd).  The DirectMsg class would manage the hops tracking on every call to msg_received.  But this seems a bit cluttered, I am not sure there are many other functions to place in the DirectMsg class.

Perhaps the Protocol class should just have an array of modems, and it can loop through them looking for the device?

**Comment by krkeegan** [comment]
Alright, so I was mistaken, the code doesn't currently support and it would take some work to enable multiple modems.  So I made it so protocol stores a single reference to modem.  

I have the tracking design done.  Which is here https://github.com/krkeegan/insteon-mqtt/tree/HopDistanceTracking

Now I just need to incorporate this so that the calculated hop_distance is used on sending.  Again, the issue is that the msg class and specifically the OutStandard/OutExtended classes lack any reference to the device object they are being sent to.  I think the best way to solve this is just to change the passed address object to be the device object.  Sadly this requires locating and changing all calls to these classes throughout the code.

**Comment by krkeegan** [comment]
@TD22057 I know you are busy, if you have a chance to chime in on a design preference I would appreciate it.

Which of the following would you prefer?

1. Pass the device object to the message class, allowing the message class to look up the hop_distance on the device.
2. Pass the hop_distance value to the message class, if none is passed assume 3 hops.

Option 1 is a bit more set it and forget it, but is a bit more complicated to debug.

Option 2 is very straightforward, but requires that every call (or at least all calls we care about) to the message class contain the necessary hop_distance.  

This only affects the OutStandard and OutExtended classes.

**Comment by krkeegan** [comment]
I ended up writing option 1, then not being happy with it and changing to option 2.  I saved the work from each one in case your preference is different from mine.  

I opted for option 2 because it makes the message class more "static" the bits and flags that are set remain set unless altered.  In option 1, the message class could dynamically change itself.  This seemed a bit wrong.

**Comment by TD22057** [comment]
I'm going to try changing the send() call to be on the on the Modem or the Device instead of the Protocol, then any messages being sent would be passed to the Modem/Device which would do the averaging and set the hops before passing it on to the Protocol.  I'm going to look through all the current send() calls and how they're being used.  I think adding a single send() to Modem or Device as the location the hop distance computation takes place will make the code simpler than trying to do it at every protocol.send() call.

**Comment by TD22057** [comment]
FYI - I extracted your code to do the hops tracking and added it with some minor modifications.  I created a MsgHistory class that each Device stores which does the hops tracking.  I changed the Protocol to emit a signal when a message is received and had the Modem connect to that.

Next step is to add a send() call to each device and put the hop computation there instead of at msg creation.

**Comment by krkeegan** [comment]
Awesome, that looks great, this seems like a simpler and more logical way to do things.

**Comment by TD22057** [comment]
I have this working - it wasn't a big change.  But - I'm concerned.  The problem I see is that the default retry count is currently 0.  So if a message fails because the hop count is too low, nothing is going to happen.  I'm a little leery of just throwing in retries everywhere without a decent way to test them out.  Most of my testing shows a hop count of zero on the incoming messages (I would have thought they should be at least 1).  Any thoughts on that?

From what I can see, the devices are all using handler.StandardCmd so I could change the default retry count to be 3 on those.  I think it needs to be > 0 if the hop computation is going to be zero...

**Comment by TD22057** [comment]
FYI - I went ahead and pushed this to the dev branch.  Still needs docs and tests but please take a look and see what you think and give it a try.  There are DEBUG level prints for the hop computations that will appear in the logs.

**Comment by krkeegan** [comment]
So a hop count of 0 is common.  It means the device and the modem are close enough to hear each other without any relays.  Hops defines the number of times the message is repeated.

I know the insteon spec leaves the number of retries undefined, but in practice all of the hardware devices I have ever seen have a retry of 3 for standard it extended commands.

I designed this to be conservative, if there is no prior hops data, then the hops used are 3.  Similarly I always round up in calculating.

I won't be able to test this out until maybe next weekend.

**Comment by TD22057** [comment]
This has been working fine for me on the dev branch so I'm going to go ahead and close it.  Feel free to re-open if you think it needs more work.
