### ISSUE TITLE
Documentation says Modem Scenes are slots 2-253 but slot 1 is programmed

### ISSUE THREAD

**Issue by peterk-code** [TD22057/insteon-mqtt#438]
I've been using a PLM that I had originally linked via HouseLinc and used in Home Assistant that had a scene stored in Slot 1. For some reason this scene is not available in discovery.

I can trigger this scene through the command interface and it functions as expected, so I think slot 1 can be a normal scene slot on the PLM.

Also Scenes 242-248 are shown as active devices in discovery even though I've never had any scenes defined for those slots.

**Comment by krkeegan** [comment]
Scenes 0/1 on the modem are used by InsteonMQTT to join i2cs devices and so cannot be used as scenes.

If scenes 242-248 are showing up, it means that your modem has something programmed there.  Check your modem's database, you can likely delete those scenes.  Otherwise you can just disable them in Home Assistant.
