### ISSUE TITLE
Support for ISY994?

### ISSUE THREAD

**Issue by starwolf73** [TD22057/insteon-mqtt#65]
Hi,
Thanks for sharing your work. I’ve been trying to find a solution to turn on/off Insteon lights with a  MQTT  button  but I can’t assign a topic to light that are from ISY994 controller. Does this project may include in long term support for ISY994 Insteon controller?

**Comment by TD22057** [comment]
Nope.  This library is focused on interfacing with the PLM modem.  The ISY is pretty expensive so I can't see myself buying one to support it.  And it would probably be easier to just start over and build a separate project since the ISY api is going to be completely different than the Insteon PLM API.

**Comment by bfranske** [comment]
Also, the ISY uses a PLM so you could just connect the PLM to a computer instead of the ISY and use it with this library. Basically with a Raspberry Pi and a PLM and this library you can have your own ISY for a fraction of the price...

**Comment by respectTheCode** [comment]
The advantage of this library is that you aren't dependent on the ISY to connect HA and INSTEON. I haven't made the jump yet but I am looking forward to removing my ISY.
